package xal.app.experimentautomator.exception;

public class CompletedException extends Exception {

}
